# Generated by Django 5.2 on 2025-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], default='individual', max_length=20),
        ),
    ]
