# Generated by Django 5.2 on 2025-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='payment_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='service_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='task_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
